### ISSUE TITLE
This tool doesn't work with images.

### ISSUE THREAD

**Issue by sanjeetsuhag** [raulbojalil/docx-builder#1]
Merging Word documents (.docx) with images in them does not work. It creates a placeholder (like an empty white space) in the final file, but the original image does not appear.

Here's what the final document looks like:

<img width="712" alt="screen shot 2017-07-27 at 2 32 01 pm" src="https://user-images.githubusercontent.com/5172619/28686254-998eed88-72d8-11e7-8caf-ce06d6eeb29b.png">

**Comment by raulbojalil** [comment]
I will look into it later in the day. Thanks.

**Comment by raulbojalil** [comment]
Hi @sanjeetsuhag. This issue is fixed now, please update to the latest version from NPM.
I just tested with png and jpeg files, please let me know if you have any problems with other file types.
