### ISSUE TITLE
Problem merging tables : changing format

### ISSUE THREAD

**Issue by saudraisn** [raulbojalil/docx-builder#2]
Hi,
I'm trying to merge a single document with the "insertDocxSync" function and the merge seems to mess with my tables format (and font).

Here's the code : 
```javascript
let builder = require('docx-builder')

var docx = new builder.Document();

docx.insertDocxSync(__dirname + '/Test/test.docx');

docx.save(__dirname + "/Test/output.docx", function (err) {
  if (err) console.log(err);
  console.log('done');
});
```
and here is my test file :
[test.docx](https://github.com/raulbojalil/docx-builder/files/1304628/test.docx)

and my output file :
[output.docx](https://github.com/raulbojalil/docx-builder/files/1304630/output.docx)

I am using word 2013, Windows 10 x64 and node v6.11.2<

Thanks! :)

**Comment by raulbojalil** [comment]
Thanks, I'll look into it in my next free time.

**Comment by saudraisn** [comment]
Thanks! Great module by the way! 👍

**Comment by saudraisn** [comment]
Hi,
I started the problem investigation and I found something concerning the fonts problem (I guess the tables problem is related to that too).

I tried merging this document : 

[test.docx](https://github.com/raulbojalil/docx-builder/files/1307596/test.docx)

into a new one (the output presented a font error) and i compared the styles.xml files generated (in the zipped .docx). 

Here's what i found : 

![styles xml diff](https://user-images.githubusercontent.com/6865470/30500427-38dd22fe-9a2c-11e7-9a43-643b0d59258b.PNG)
When i pasted the missing part in the output => styles.xml files and rezipped the output, the result looked as expected.
Perhaps a merge of the styles.xml would be necessary too and not just the document.xml files :) 

EDIT : 
Also in the settings.xml files : 
![image](https://user-images.githubusercontent.com/6865470/30500737-a1d7d726-9a2d-11e7-9e82-afb261abdb92.png)

**Comment by raulbojalil** [comment]
Thanks @saudraisn, this is very helpful. Please stand by while I fix it.

**Comment by raulbojalil** [comment]
Done!. I published a new version to NPM (1.0.6). Please try it and let me know if you find any other issue. Thanks.

**Comment by saudraisn** [comment]
@raulbojalil, Amazing! It all seems to work for now. I'll let you know if i encounter other issues during my development. Have a nice day! 👍

**Comment by saudraisn** [comment]
Hi @raulbojalil, I ran into two small issues that concerns sections breaks and columns :
1) When I insert a continuous section break into a .docx document and i merge it into a new one, it generates an invalid result. When i try to open it with Microsoft Word I see this : 
![image](https://user-images.githubusercontent.com/6865470/30567691-8b70066a-9c9f-11e7-8bb2-130f8ab789d4.png)

And when i inspect the generated document.xml file, there are 2 closing xml tags missing at the very end (plus the content is missing (I guess the two are related)):
![image](https://user-images.githubusercontent.com/6865470/30567828-3906ef5a-9ca0-11e7-9683-a8f997df62af.png)

Here's the test file : 
[test.docx](https://github.com/raulbojalil/docx-builder/files/1312482/test.docx)
 
And the obtained result  : 
[result.docx](https://github.com/raulbojalil/docx-builder/files/1312484/result.docx)


2) When I try to merge a document that has 2 columns initially, it gets back to a single column document in the generated file (and the column break acts like a page break).

Here's the test file : 
[test.docx](https://github.com/raulbojalil/docx-builder/files/1312495/test.docx)

And the result : 
[result.docx](https://github.com/raulbojalil/docx-builder/files/1312496/result.docx)

And here's what i found while investigating this issue : 
![image](https://user-images.githubusercontent.com/6865470/30568208-eb116d5a-9ca1-11e7-9a64-8dd52e5b5bd7.png)

Hopefully this will help :)
